language: python
# if command bellow need to executed in sudo
# add this line.
# sudo: required
python:
  - 3.7
install:
  # - docker-compose build
  - pip install poetry
  - poetry install
script:
  - python manage.py test
  # - docker-compose run test --rm -v
