version: '3'

services:
  mongo:
    image: mongo
    restart: always
    deploy:
      resources:
        limits:
          memory: 20G
        reservations:
          memory: 5G
  db:
    build: './db'
    restart: always
    expose: 
          - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: test
  web:
    build: .
    command: ["./wait-for-it.sh", "mongo:27017", "--", "python3", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "${OUTPUT_PORT}:8000"
    depends_on:
      - mongo
      - db
    restart: always
    deploy:
      resources:
        limits:
          memory: 20G
        reservations:
          memory: 5G